name: Notify
on:
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '27 * * * *'
jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v5
      - name: Installing dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r pip-requirements.txt
      - name: Run notify
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: |
          python3 main.py config.yaml

      - name: Prepare commit
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
      - name: Commit report changes
        run: git diff --cached --quiet || git commit -m 'Update last_timestamp'
      - name: Push commit
        if: ${{ github.ref == 'refs/heads/main' }}
        run: git push
